* Encoding: UTF-8.
REGRESSION
 /STATISTICS COEFF OUTS R ANOVA ZPP
 /DEPENDENT BLM_Inter
 /METHOD=ENTER cobras_blatant BLM_Black.

REGRESSION
 /STATISTICS COEFF OUTS R ANOVA ZPP
 /DEPENDENT BLM_Inter
 /METHOD=ENTER cobras_institutional BLM_Black.

REGRESSION
 /STATISTICS COEFF OUTS R ANOVA ZPP
 /DEPENDENT BLM_Inter
 /METHOD=ENTER cobras_unaware BLM_Black.

REGRESSION
 /STATISTICS COEFF OUTS R ANOVA ZPP
 /DEPENDENT BLM_Inter
 /METHOD=ENTER mrs_tot BLM_Black.

